apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-container
          image: your-docker-registry/your-image-name:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: EXCHANGE_NAME
            - name: PORT
              value: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
