apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
        - name: community-container
          image: your-docker-registry/your-image-name:latest
          ports:
            - containerPort: 8005
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: EXCHANGE_NAME
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: API_SECRET
            - name: PORT
              value: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: community-service
spec:
  selector:
    app: community
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
