apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events-container
          image: aswin5352/zoro_events
          ports:
            - containerPort: 8006
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXCHANGE_NAME
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_SECRET
            - name: PORT
              value: "8006"
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006