apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages-container
          image: your-docker-registry/your-image-name:latest
          ports:
            - containerPort: 8004
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: zoro-secret
                  key: EXCHANGE_NAME
            - name: PORT
              value: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  selector:
    app: messages
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
