apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages-container
          image: aswin5352/zoro_messages
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXCHANGE_NAME
            - name: PORT
              value: "8004"
---
apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  selector:
    app: messages
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
