apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-container
          image: aswin5352/zoro_notifications
          ports:
            - containerPort: 8003
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXCHANGE_NAME
            - name: PORT
              value: "8003"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
