apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts-container
          image: aswin5352/zoro_posts
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXCHANGE_NAME
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_SECRET
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: BUCKET_NAME
            - name: BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: BUCKET_REGION
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: ACCESS_KEY
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: SECRET_ACCESS_KEY
            - name: PORT
              value: "8002"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
