apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: aswin5352/zoro_users
          ports:
            - containerPort: 8001
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: MSG_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MSG_QUEUE_URL
            - name: EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: EXCHANGE_NAME
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: API_SECRET
            - name: PORT
              value: "8001"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
