version: "3"
services:
  client:
    image: aswin5352/zoro_client
    container_name: client
    ports:
      - 5173:80
    restart: always
    env_file:
      - ./users/.env
  users:
    image: aswin5352/zoro_users
    container_name: users
    ports:
      - 8001:8001
    restart: always
    env_file:
      - ./users/.env
  posts:
    image: aswin5352/zoro_posts
    container_name: posts
    ports:
      - 8002:8002
    restart: always
    env_file:
      - ./posts/.env
  messaging:
    image: aswin5352/zoro_messages
    container_name: messaging
    ports:
      - 8004:8004
    restart: always
    env_file:
      - ./messages/.env
  notification:
    image: aswin5352/zoro_notifications
    container_name: notification
    ports:
      - 8003:8003
    restart: always
    env_file:
      - ./notification/.env
  community:
    image: aswin5352/zoro_community
    container_name: community
    ports:
      - 8005:8005
    restart: always
    env_file:
      - ./community/.env
  events:
    image: aswin5352/zoro_events
    container_name: events
    ports:
      - 8006:8006
    restart: always
    env_file:
      - ./events/.env
  admin:
    image: aswin5352/zoro_admin
    container_name: admin
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./admin/.env
