version: "3"
services:


  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    ports:
      - 5173:80
    restart: always
    env_file:
      - ./users/.env
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - 8001:8001
    restart: always
    env_file:
      - ./users/.env
  posts:
    build:
      dockerfile: Dockerfile
      context: ./posts
    container_name: posts
    ports:
      - 8002:8002
    restart: always
    env_file:
      - ./posts/.env
  messaging:
    build:
      dockerfile: Dockerfile
      context: ./messages
    container_name: messaging
    ports:
      - 8004:8004
    restart: always
    env_file:
      - ./messages/.env
  notification:
    build:
      dockerfile: Dockerfile
      context: ./notification
    container_name: notification
    ports:
      - 8003:8003
    restart: always
    env_file:
      - ./notification/.env
  community:
    build:
      dockerfile: Dockerfile
      context: ./community
    container_name: community
    ports:
      - 8005:8005
    restart: always
    env_file:
      - ./community/.env
  events:
    build:
      dockerfile: Dockerfile
      context: ./events
    container_name: events
    ports:
      - 8006:8006
    restart: always
    env_file:
      - ./events/.env
  admin:
    build:
      dockerfile: Dockerfile
      context: ./admin
    container_name: admin
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./admin/.env