name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yaml' # Add path to your Docker Compose file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Compose
        run: docker-compose -f docker-compose.yaml build
      - name: Push Docker Compose
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f docker-compose.yaml push
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d

          
       
      
