name: deploy-events

on:
  push: 
    branches:
      - main
    paths: 
      - 'events/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd events && docker build -t aswin5352/zoro_events .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      - run: docker push aswin5352/zoro_events
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes  cluster kubeconfig save project-zoro
      - run: kubectl rollout restart deployment events-deployment
          
       
      