name: deploy-users

on:
  push: 
    branches:
      - main
    paths: 
      - 'users/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd users && docker build -t aswin5352/zoro_users .
      - run: docker login -u $DOCKER_USERNAME -p $DOKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      - run: docker push aswin5352/zoro_users
       
      
